---

# based on https://github.com/hpcng/warewulf/blob/development/.github/workflows/releasebuild.yml
# Thanks!

name: releasebuild

on:
  release:
    types:
      - published
#          echo "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

jobs:
  distbuild:
    name: Checkout code and build tar
    runs-on: ubuntu-latest
    steps:
      - name: Set the version
        id: version_number
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "VERSION=${TAG%-*}" >> $GITHUB_ENV
          echo "RELEASE=${TAG#*-}" >> $GITHUB_ENV
          echo "RELDATE=`date -I`" >> $GITHUB_ENV
          cat $GITHUB_ENV

      - name: Set the git source location
        id: source_loc
        run: |
          echo "SRC=${GITHUB_REF}" >> $GITHUB_ENV

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build tar
        run: ci/maketar.sh build.tar ${{ env.VERSION }} ${{ env.RELEASE }} ${{ env.RELDATE }} 

      - name: Upload mock script
        uses: actions/upload-artifact@v4
        with:
          name: mockbuild.sh 
          path: ci/mockbuild.sh 

      - name: Upload tar
        uses: actions/upload-artifact@v4
        with:
          name: build.tar
          path: build.tar

      - name: upload spec file
        uses: actions/upload-artifact@v4
        with:
          name: pgplot.spec
          path: pgplot.spec


  rpmbuild:
      name: Build using Rocky Linux
      needs: distbuild
      runs-on: ubuntu-latest
      container:
        image: rockylinux/rockylinux
        options: --privileged
      steps:
        - name: Set the version
          id: version_number
          run: |
             TAG=${GITHUB_REF#refs/tags/v}
             echo "VERSION=${TAG%-*}" >> $GITHUB_ENV
             echo "RELEASE=${TAG#*-}" >> $GITHUB_ENV
 
        - name: Download mock build script
          uses: actions/download-artifact@v4
          with:
            name: mockbuild.sh

        - name: Download tar
          uses: actions/download-artifact@v4
          with:
            name: build.tar

        - name: Download spec file
          uses: actions/download-artifact@v4
          with:
            name: pgplot.spec

        - name: Set execute bit
          run: chmod +x mockbuild.sh

        - name: Run rpm build script
          run: ./mockbuild.sh  build.tar ${{ env.VERSION }}

        - name: move rpms to main dir
          run: mv outputs/*.rpm .

        - name: Upload Assets To Release
          if: "!github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "*.rpm"
            draft: false
            update_latest_release: true
            tags: true

        - name: Upload Assets To Pre-Release
          if: "github.event.release.prerelease"
          uses: xresloader/upload-to-github-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            file: "*.rpm"
            draft: false
            update_latest_release: false
            prerelease: true
            tags: true
            
